#!/bin/bash
read -p "Hello write your username: " username
echo "Hello, $username!"
echo "This is a game with a mix of many mini-games. Which would you like to play?"
echo "1) Number Guessing Game"
echo "2) Rock Paper Scissors"
echo "3) Word Guessing Game"
read -p "Please choose a game (1-3): " choice

if [ "$choice" -eq 1 ]; then 
    echo "Welcome to the game where you guess the number I am thinking of!"
    random_number=$((RANDOM % 100 + 1))
    guess=0

    while [ "$guess" -ne "$random_number" ]; do
        read -p "Guess a number between 1 and 100: " guess
        if [ "$guess" -gt "$random_number" ]; then 
            echo "Too high! Try again."
        elif [ "$guess" -lt "$random_number" ]; then 
            echo "Too low! Try again."
        fi  
        
    done  

    echo "Congratulations! You've guessed the number!"

elif [ "$choice" -eq 2 ]; then
    echo "Rock Paper Scissors isnt ready yet."

elif [ "$choice" -eq 3 ]; then
    echo "Word Guessing Game isnt ready yet."

else
    echo "Invalid choice. Please select a number between 1 and 3."
fi  # Closing the main if statement

